server:
  port: 8080
#数据库配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root #数据库用户名
    password:  #数据库密码
    url: jdbc:mysql://localhost/device?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-circular-references: true
#qq邮箱
  mail:
    host: smtp.qq.com  # 配置 smtp 服务器地址
    port: 587  # smtp 服务器端口
    username:  #配置你的邮箱地址
    password:  #配置申请到的授权码
    protocol: smtp
    defaultEncoding: utf-8
#Redis
  redis:
    host:   #主机名
    port:  #端口号
    password:   #redis密码
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    jackson:
      default-property-inclusion: non_null # JSON处理时忽略非空字段
#RabbitMQ
  rabbitmq:
    host:   # 主机名
    port:    # 端口
    virtual-host: /  #虚拟主机
    username:  # 用户名
    password:   # 密码
#日志
logging:
  level:
    com:
      starqeem: debug  #开启日志,debug级别